# Generated by Django 5.2.6 on 2025-09-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJANGO_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='genre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='genre', to='DJANGO_App.genre', verbose_name='жанр'),
        ),
    ]
