# Generated by Django 5.2.7 on 2025-10-10 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJANGO_App', '0002_alter_catalogue_genre_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='Наименование Товара')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товаров',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50, verbose_name='Наименование Поставщика')),
                ('INN', models.IntegerField(max_length=12, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщиков',
            },
        ),
        migrations.AlterModelOptions(
            name='catalogue',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Наименовании Категории', 'verbose_name_plural': 'Наименования Категорий'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Наименование Жанра', 'verbose_name_plural': 'Наименования Жанров'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Название Платформы', 'verbose_name_plural': 'Названия Платформ'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Название Тайтла', 'verbose_name_plural': 'Названия Тайтлов'},
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField()),
                ('quanity', models.PositiveIntegerField()),
                ('shipping_datetime', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DJANGO_App.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузок',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.PositiveIntegerField()),
                ('order_datetime', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DJANGO_App.item', verbose_name='Товар')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DJANGO_App.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказов',
            },
        ),
    ]
