# Generated by Django 5.2.7 on 2025-10-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJANGO_App', '0003_item_supplier_alter_catalogue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='INN',
            field=models.IntegerField(verbose_name='ИНН'),
        ),
    ]
