# Generated by Django 5.2.7 on 2025-10-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJANGO_App', '0004_alter_supplier_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(verbose_name='Время/Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quanity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='adress',
            field=models.CharField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='quanity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_datetime',
            field=models.DateTimeField(verbose_name='Время/Дата заказа'),
        ),
    ]
